server:
  port: 8081
spring:
  application:
    name: wph-service-consumer
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@123.206.255.244:7776/eureka/
feign:
  hystrix:
    enabled: true
---
#注意下面这个路径，一定要写对，不要多斜杠或者少斜杠，都不行，会找不到路径
spring:
  thymeleaf:
    prefix: classpath:/static/html/
    suffix: .html
---
spring:
  redis:
      #数据库索引
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
          #最大连接数
        max-active: 8
          #最大空闲
        max-idle: 8

          #最小空闲
        min-idle: 0