server:
  port: 7080
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@123.206.255.244:7776/eureka/
spring:
  datasource:
    # 使用druid数据源
    url: jdbc:mysql://localhost:3306/myone
    username: HQY
    password: 610724
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #最大连接池数量
      max-active: 10
      #最小连接池数量
      min-idle: 1
      initial-size: 1
      max-wait: 60000
      #销毁线程中如果检测到当前连接的最后活跃时间和当前时间的差值大于minEvictableIdleTimeMillis，则关闭当前连接。
      minEvictableIdleTimeMillis: 300000
      #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
      validationQuery: select 'x'
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
  application:
    name: wph-order-provider
  profiles:
    active: dev
  rabbitmq:
    host: 123.206.255.244
    port: 5672
    username: admin
    password: 123456
    virtual-host: /rabbit-1
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
mybatis:
  mapperLocations: classpath:mapper/*.xml