server:
  port: 8082
spring:
  application:
    name: wph_pay_consumer
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@47.94.235.82:7776/eureka/
feign:
  hystrix:
    enabled: true