server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@123.206.255.244:7776/eureka/
      instance:
        hostname: localhost
        instance-id: localhost:${server.port}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: rootroot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 10
      min-idle: 1
      initial-size: 1
      max-wait: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      timeBetweenEvictionRunsMillis: 60000
  application:
    name: wph-tickets-provider
  profiles:
    active: dev
mybatis:
  mapperLocations: classpath:mapper/*.xml