server:
  port: 8083
spring:
  application:
    name: wph-tickets-consumer
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@123.206.255.244:7776/eureka/
      instance:
        hostname: localhost
        instance-id: localhost:${server.port}
feign:
  hystrix:
    enabled: true
---
spring:
  thymeleaf:
    prefix: classpath:/static/html/
    suffix: .html
---