server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@123.206.255.244:7776/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/js-deposit
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 10
      min-idle: 1
      initial-size: 1
      max-wait: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      timeBetweenEvictionRunsMillis: 60000
  application:
    name: wph_shopcar_provider
  profiles:
    active: dev
  rabbitmq:
    host: 123.206.255.244
    port: 5672
    username: admin
    password: 123456
    virtual-host: /rabbit-1
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        prefetch: 1