server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@123.206.255.244:7776/eureka/
      instance:
        hostname: localhost
        instance-id: localhost:${server.port}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myone
    username: HQY
    password: 610724
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 10
      min-idle: 1
      initial-size: 1
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
  application:
    name: wph-shopcar-provider
  profiles:
    active: dev
  rabbitmq:
    host: 123.206.255.244
    port: 5672
    username: admin
    password: 123456
    virtual-host: /rabbit-1
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
#  zipkin:
#    base-url: http://192.168.51.252:7070
logging:
  level: info