logging:
  level: info
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@123.206.255.244:7776/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: rootroot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 10
      min-idle: 1
      initial-size: 1
      max-wait: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      timeBetweenEvictionRunsMillis: 60000
  application:
    name: wph-service-provider
  profiles:
    active: dev
---
#注意下面这个路径，一定要写对，不要多斜杠或者少斜杠，都不行，会找不到路径
spring:
  thymeleaf:
    prefix: classpath:/static/html/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
---
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  mapperLocations: classpath:mapper/*.xml
---
#spring:
#  sleuth:
#    sampler:
#      percentage: 1.0
#  zipkin:
#    base-url: http://localhost:7070