server:
  port: 8081
spring:
  application:
    name: wph-seckill-consumer
  sleuth:
    sampler:
      percentage: 1.0
  datasource:
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@123.206.255.244:7776/eureka/
feign:
  hystrix:
    enabled: true